---
title: "Exon class size"
author: "Jacob Green"
date: '2023-03-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = "/home/jgreen/EAGER_OBJ1a/04_coverage_analysis/02_exon_stats")
```

## R Markdown

```{r Set Libraries and Working Directory}
library(MASS)
library(fields)
library(ggplot2)
library(grid)
library(plyr)
library(dplyr)
library(scales)
library(zoo)
```

```{r Make data frames}
setwd("/home/jgreen/EAGER_OBJ1a/04_coverage_analysis/02_exon_stats")
df1 <- read.table("capture1_filter.merged.merged.ExonMeanCoverage.txt", header = TRUE)
df1 <-as.data.frame(df1)
df2 <- read.table("capture2_filter.merged.merged.ExonMeanCoverage.txt", header = TRUE)
df2 <-as.data.frame(df2)
df3 <- read.table("capture3_filter.merged.merged.ExonMeanCoverage.txt", header = TRUE)
df3 <-as.data.frame(df3)
df4 <- read.table("capture4_filter.merged.merged.ExonMeanCoverage.txt", header = TRUE)
df4 <-as.data.frame(df4)
df5 <- read.table("all.merged.ExonMeanCoverage.txt", header = TRUE)
df5 <-as.data.frame(df5)
```

```{r Merge11}
setwd("/home/jgreen/EAGER_OBJ1a/04_coverage_analysis/02_exon_stats")
merged_cap11df <- merge(df1, df1[, c("Start","DNA_Coverage", "Exon_Size_Class")],by = "Start")
TotalExon <- merged_cap11df[merged_cap11df$DNA_Coverage.x != 0 & merged_cap11df$DNA_Coverage.y != 0,]
TotalExon <- TotalExon[, -5]

TotalExon$Exon_Size_Class <-factor(TotalExon$Exon_Size_Class.y, levels=c("Lower","Middle","Upper"))


TotalExon$Exon_Size_Class <- revalue(TotalExon$Exon_Size_Class.y, c("Lower"="Lower 10%", "Upper"="Upper 10%", "Middle"="Middle 80%"))

get_density <- function(x, y, n = 100) {
  dens <- MASS::kde2d(x = x, y = y, n = n)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}
TotalExon$density <- get_density(TotalExon$DNA_Coverage.x,TotalExon$DNA_Coverage.y)

cbPalette <- c("#009E73","#D55E00","#56B4E9", "#0072B2","#E69F00", "#F0E442" , "#999999","#CC79A7")
t <- cbPalette[1]
cbPalette[1] <- cbPalette[2]
cbPalette[2] <- t

TotalExon$DNA_Coverage.y <- TotalExon$DNA_Coverage.y/6
TotalExon$DNA_Coverage.x <- TotalExon$DNA_Coverage.x/6


b1 <- bb<- ggplot(TotalExon, aes(x=DNA_Coverage.x+1,y=DNA_Coverage.y+1,alpha = 1/density),fill=Exon_Size_Class,color=Exon_Size_Class) + 
  geom_point(aes(color=TotalExon$Exon_Size_Class,fill=TotalExon$Exon_Size_Class,shape=TotalExon$Exon_Size_Class)) +
  geom_smooth(method="auto", alpha = 0.5, size = 0, se=TRUE)+
  geom_abline(linetype = "dashed", color = "red") +
  stat_smooth(geom="line", alpha=0.75, size=0.5, linetype="dashed") +
  scale_alpha_continuous(guide = "none",range = c(.2, .95)) + 
  scale_shape_manual(values=c(15,16,17), name="Exon Size Percentile") +
  scale_fill_manual(values=cbPalette , name="Exon Size Percentile")+
  scale_color_manual(values=cbPalette, name="Exon Size Percentile") +
  scale_x_log10(limits=c(1,1300),expand=c(0.02,0), breaks = c(0,1,11,101,1001),
                labels = c("0","0","10","100","1,000"))+
  scale_y_log10(limits=c(1,1800),expand=c(0.02,0), breaks = c(0,1,11,101,1001),
                labels = c("0","0","10","100","1,000"))+
  xlab("Mean (150,150) DNA Reads per Exon Base Pair")+
  ylab("Mean (150,150) DNA Reads per Exon Base Pair") +
  theme_bw() +
  theme(legend.position = c(0.9,0.15))  

png(filename="Figure3_cap11.png", type="cairo",units="px", width=5600, 
    height=3000, res=600, bg="transparent")
b1
dev.off()
```

# join the two data frames based on the id column
```{r Merge12}
setwd("/home/jgreen/EAGER_OBJ1a/04_coverage_analysis/02_exon_stats")
merged_cap12df <- merge(df1, df2[, c("Start","DNA_Coverage", "Exon_Size_Class")],by = "Start")
TotalExon <- merged_cap12df[merged_cap12df$DNA_Coverage.x != 0 & merged_cap12df$DNA_Coverage.y != 0,]
TotalExon <- TotalExon[, -5]

TotalExon$Exon_Size_Class <-factor(TotalExon$Exon_Size_Class.y, levels=c("Lower","Middle","Upper"))


TotalExon$Exon_Size_Class <- revalue(TotalExon$Exon_Size_Class.y, c("Lower"="Lower 10%", "Upper"="Upper 10%", "Middle"="Middle 80%"))

get_density <- function(x, y, n = 100) {
  dens <- MASS::kde2d(x = x, y = y, n = n)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}
TotalExon$density <- get_density(TotalExon$DNA_Coverage.x,TotalExon$DNA_Coverage.y)

cbPalette <- c("#009E73","#D55E00","#56B4E9", "#0072B2","#E69F00", "#F0E442" , "#999999","#CC79A7")
t <- cbPalette[1]
cbPalette[1] <- cbPalette[2]
cbPalette[2] <- t

TotalExon$DNA_Coverage.y <- TotalExon$DNA_Coverage.y/6
TotalExon$DNA_Coverage.x <- TotalExon$DNA_Coverage.x/6


b1 <- bb<- ggplot(TotalExon, aes(x=DNA_Coverage.x+1,y=DNA_Coverage.y+1,alpha = 1/density),fill=Exon_Size_Class,color=Exon_Size_Class) + 
  geom_point(aes(color=TotalExon$Exon_Size_Class,fill=TotalExon$Exon_Size_Class,shape=TotalExon$Exon_Size_Class)) +
  geom_smooth(method="auto", alpha = 0.5, size = 0, se=TRUE)+
  geom_abline(linetype = "dashed", color = "red") +
  stat_smooth(geom="line", alpha=0.75, size=0.5, linetype="dashed") +
  scale_alpha_continuous(guide = "none",range = c(.2, .95)) + 
  scale_shape_manual(values=c(15,16,17), name="Exon Size Percentile") +
  scale_fill_manual(values=cbPalette , name="Exon Size Percentile")+
  scale_color_manual(values=cbPalette, name="Exon Size Percentile") +
  scale_x_log10(limits=c(1,1300),expand=c(0.02,0), breaks = c(0,1,11,101,1001),
                labels = c("0","0","10","100","1,000"))+
  scale_y_log10(limits=c(1,1800),expand=c(0.02,0), breaks = c(0,1,11,101,1001),
                labels = c("0","0","10","100","1,000"))+
  xlab("Mean (150/150) DNA Reads per Exon Base Pair")+
  ylab("Mean (150/300) DNA Reads per Exon Base Pair") +
  theme_bw() +
  theme(legend.position = c(0.9,0.15))  

png(filename="Figure3_cap12.png", type="cairo",units="px", width=5600, 
    height=3000, res=600, bg="transparent")
b1
dev.off()
```

```{r Merge13}
setwd("/home/jgreen/EAGER_OBJ1a/04_coverage_analysis/02_exon_stats")
merged_cap13df <- merge(df1, df3[, c("Start","DNA_Coverage", "Exon_Size_Class")],by = "Start")
TotalExon <- merged_cap13df[merged_cap13df$DNA_Coverage.x != 0 & merged_cap13df$DNA_Coverage.y != 0,]
TotalExon <- TotalExon[, -5]

TotalExon$Exon_Size_Class <-factor(TotalExon$Exon_Size_Class.y, levels=c("Lower","Middle","Upper"))


TotalExon$Exon_Size_Class <- revalue(TotalExon$Exon_Size_Class.y, c("Lower"="Lower 10%", "Upper"="Upper 10%", "Middle"="Middle 80%"))

get_density <- function(x, y, n = 100) {
  dens <- MASS::kde2d(x = x, y = y, n = n)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}
TotalExon$density <- get_density(TotalExon$DNA_Coverage.x,TotalExon$DNA_Coverage.y)

cbPalette <- c("#009E73","#D55E00","#56B4E9", "#0072B2","#E69F00", "#F0E442" , "#999999","#CC79A7")
t <- cbPalette[1]
cbPalette[1] <- cbPalette[2]
cbPalette[2] <- t

TotalExon$DNA_Coverage.y <- TotalExon$DNA_Coverage.y/6
TotalExon$DNA_Coverage.x <- TotalExon$DNA_Coverage.x/6


b2 <- bb<- ggplot(TotalExon, aes(x=DNA_Coverage.x+1,y=DNA_Coverage.y+1,alpha = 1/density),fill=Exon_Size_Class,color=Exon_Size_Class) + 
  geom_point(aes(color=TotalExon$Exon_Size_Class,fill=TotalExon$Exon_Size_Class,shape=TotalExon$Exon_Size_Class)) +
  geom_smooth(method="auto", alpha = 0.5, size = 0, se=TRUE)+
  geom_abline(linetype = "dashed", color = "red") +
  stat_smooth(geom="line", alpha=0.75, size=0.5, linetype="dashed") +
  scale_alpha_continuous(guide = "none",range = c(.2, .95)) + 
  scale_shape_manual(values=c(15,16,17), name="Exon Size Percentile") +
  scale_fill_manual(values=cbPalette , name="Exon Size Percentile")+
  scale_color_manual(values=cbPalette, name="Exon Size Percentile") +
  scale_x_log10(limits=c(1,1300),expand=c(0.02,0), breaks = c(0,1,11,101,1001),
                labels = c("0","0","10","100","1,000"))+
  scale_y_log10(limits=c(1,1800),expand=c(0.02,0), breaks = c(0,1,11,101,1001),
                labels = c("0","0","10","100","1,000"))+
  xlab("Mean (150/150) DNA Reads per Exon Base Pair")+
  ylab("Mean (300/150) DNA Reads per Exon Base Pair") +
  theme_bw() +
  theme(legend.position = c(0.9,0.15))  

png(filename="Figure3_cap13.png", type="cairo",units="px", width=5600, 
    height=3000, res=600, bg="transparent")
b2
dev.off()
```

```{r Merge14}
setwd("/home/jgreen/EAGER_OBJ1a/04_coverage_analysis/02_exon_stats")
merged_cap14df <- merge(df1, df4[, c("Start","DNA_Coverage", "Exon_Size_Class")],by = "Start")
TotalExon <- merged_cap14df[merged_cap14df$DNA_Coverage.x != 0 & merged_cap14df$DNA_Coverage.y != 0,]
TotalExon <- TotalExon[, -5]


TotalExon$Exon_Size_Class <-factor(TotalExon$Exon_Size_Class.y, levels=c("Lower","Middle","Upper"))


TotalExon$Exon_Size_Class <- revalue(TotalExon$Exon_Size_Class.y, c("Lower"="Lower 10%", "Upper"="Upper 10%", "Middle"="Middle 80%"))

get_density <- function(x, y, n = 100) {
  dens <- MASS::kde2d(x = x, y = y, n = n)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}
TotalExon$density <- get_density(TotalExon$DNA_Coverage.x,TotalExon$DNA_Coverage.y)

cbPalette <- c("#009E73","#D55E00","#56B4E9", "#0072B2","#E69F00", "#F0E442" , "#999999","#CC79A7")
t <- cbPalette[1]
cbPalette[1] <- cbPalette[2]
cbPalette[2] <- t

TotalExon$DNA_Coverage.y <- TotalExon$DNA_Coverage.y/6
TotalExon$DNA_Coverage.x <- TotalExon$DNA_Coverage.x/6


b3 <- bb<- ggplot(TotalExon, aes(x=DNA_Coverage.x+1,y=DNA_Coverage.y+1,alpha = 1/density),fill=Exon_Size_Class,color=Exon_Size_Class) + 
  geom_point(aes(color=TotalExon$Exon_Size_Class,fill=TotalExon$Exon_Size_Class,shape=TotalExon$Exon_Size_Class)) +
  geom_smooth(method="auto", alpha = 0.5, size = 0, se=TRUE)+
  geom_abline(linetype = "dashed", color = "red") +
  stat_smooth(geom="line", alpha=0.75, size=0.5, linetype="dashed") +
  scale_alpha_continuous(guide = "none",range = c(.2, .95)) + 
  scale_shape_manual(values=c(15,16,17), name="Exon Size Percentile") +
  scale_fill_manual(values=cbPalette , name="Exon Size Percentile")+
  scale_color_manual(values=cbPalette, name="Exon Size Percentile") +
  scale_x_log10(limits=c(1,1300),expand=c(0.02,0), breaks = c(0,1,11,101,1001),
                labels = c("0","0","10","100","1,000"))+
  scale_y_log10(limits=c(1,1800),expand=c(0.02,0), breaks = c(0,1,11,101,1001),
                labels = c("0","0","10","100","1,000"))+
  xlab("Mean (150/150) DNA Reads per Exon Base Pair")+
  ylab("Mean (300/300) DNA Reads per Exon Base Pair") +
  theme_bw() +
  theme(legend.position = c(0.9,0.15))  

png(filename="Figure3_cap14.png", type="cairo",units="px", width=5600, 
    height=3000, res=600, bg="transparent")
b3
dev.off()
```

```{r Merge24}
setwd("/home/jgreen/EAGER_OBJ1a/04_coverage_analysis/02_exon_stats")
merged_cap24df <- merge(df2, df4[, c("Start","DNA_Coverage", "Exon_Size_Class")],by = "Start")
TotalExon <- merged_cap24df[merged_cap24df$DNA_Coverage.x != 0 & merged_cap24df$DNA_Coverage.y != 0,]
TotalExon <- TotalExon[, -5]


TotalExon$Exon_Size_Class <-factor(TotalExon$Exon_Size_Class.y, levels=c("Lower","Middle","Upper"))


TotalExon$Exon_Size_Class <- revalue(TotalExon$Exon_Size_Class.y, c("Lower"="Lower 10%", "Upper"="Upper 10%", "Middle"="Middle 80%"))

get_density <- function(x, y, n = 100) {
  dens <- MASS::kde2d(x = x, y = y, n = n)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}
TotalExon$density <- get_density(TotalExon$DNA_Coverage.x,TotalExon$DNA_Coverage.y)

cbPalette <- c("#009E73","#D55E00","#56B4E9", "#0072B2","#E69F00", "#F0E442" , "#999999","#CC79A7")
t <- cbPalette[1]
cbPalette[1] <- cbPalette[2]
cbPalette[2] <- t

TotalExon$DNA_Coverage.y <- TotalExon$DNA_Coverage.y/6
TotalExon$DNA_Coverage.x <- TotalExon$DNA_Coverage.x/6


b4 <- bb<- ggplot(TotalExon, aes(x=DNA_Coverage.x+1,y=DNA_Coverage.y+1,alpha = 1/density),fill=Exon_Size_Class,color=Exon_Size_Class) + 
  geom_point(aes(color=TotalExon$Exon_Size_Class,fill=TotalExon$Exon_Size_Class,shape=TotalExon$Exon_Size_Class)) +
  geom_smooth(method="auto", alpha = 0.5, size = 0, se=TRUE)+
  geom_abline(linetype = "dashed", color = "red") +
  stat_smooth(geom="line", alpha=0.75, size=0.5, linetype="dashed") +
  scale_alpha_continuous(guide = "none",range = c(.2, .95)) + 
  scale_shape_manual(values=c(15,16,17), name="Exon Size Percentile") +
  scale_fill_manual(values=cbPalette , name="Exon Size Percentile")+
  scale_color_manual(values=cbPalette, name="Exon Size Percentile") +
  scale_x_log10(limits=c(1,1300),expand=c(0.02,0), breaks = c(0,1,11,101,1001),
                labels = c("0","0","10","100","1,000"))+
  scale_y_log10(limits=c(1,1800),expand=c(0.02,0), breaks = c(0,1,11,101,1001),
                labels = c("0","0","10","100","1,000"))+
  xlab("Mean (150/300) DNA Reads per Exon Base Pair")+
  ylab("Mean (300/300) DNA Reads per Exon Base Pair") +
  theme_bw() +
  theme(legend.position = c(0.9,0.15))  

png(filename="Figure3_cap24.png", type="cairo",units="px", width=5600, 
    height=3000, res=600, bg="transparent")
b4
dev.off() 
```

```{r}
setwd("/home/jgreen/EAGER_OBJ1a/04_coverage_analysis/02_exon_stats")
merged_cap15df <- merge(df1, df5[, c("Start","DNA_Coverage", "Exon_Size_Class")],by = "Start")
TotalExon <- merged_cap24df[merged_cap15df$DNA_Coverage.x != 0 & merged_cap15df$DNA_Coverage.y != 0,]
TotalExon <- TotalExon[, -5]


TotalExon$Exon_Size_Class <-factor(TotalExon$Exon_Size_Class.y, levels=c("Lower","Middle","Upper"))


TotalExon$Exon_Size_Class <- revalue(TotalExon$Exon_Size_Class.y, c("Lower"="Lower 10%", "Upper"="Upper 10%", "Middle"="Middle 80%"))

get_density <- function(x, y, n = 100) {
  dens <- MASS::kde2d(x = x, y = y, n = n)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}
TotalExon$density <- get_density(TotalExon$DNA_Coverage.x,TotalExon$DNA_Coverage.y)

cbPalette <- c("#009E73","#D55E00","#56B4E9", "#0072B2","#E69F00", "#F0E442" , "#999999","#CC79A7")
t <- cbPalette[1]
cbPalette[1] <- cbPalette[2]
cbPalette[2] <- t

TotalExon$DNA_Coverage.y <- TotalExon$DNA_Coverage.y/6
TotalExon$DNA_Coverage.x <- TotalExon$DNA_Coverage.x/6


b5 <- bb<- ggplot(TotalExon, aes(x=DNA_Coverage.x+1,y=DNA_Coverage.y+1,alpha = 1/density),fill=Exon_Size_Class,color=Exon_Size_Class) + 
  geom_point(aes(color=TotalExon$Exon_Size_Class,fill=TotalExon$Exon_Size_Class,shape=TotalExon$Exon_Size_Class)) +
  geom_smooth(method="auto", alpha = 0.5, size = 0, se=TRUE)+
  stat_smooth(geom="line", alpha=0.75, size=0.5, linetype="dashed") +
  scale_alpha_continuous(guide = "none",range = c(.2, .95)) + 
  scale_shape_manual(values=c(15,16,17), name="Exon Size Percentile") +
  scale_fill_manual(values=cbPalette , name="Exon Size Percentile")+
  scale_color_manual(values=cbPalette, name="Exon Size Percentile") +
  scale_x_log10(limits=c(1,1300),expand=c(0.02,0), breaks = c(0,1,11,101,1001),
                labels = c("0","0","10","100","1,000"))+
  scale_y_log10(limits=c(1,1800),expand=c(0.02,0), breaks = c(0,1,11,101,1001),
                labels = c("0","0","10","100","1,000"))+
  xlab("Mean Capture1 DNA Reads per Exon Base Pair")+
  ylab("Mean All DNA Reads per Exon Base Pair") +
  theme_bw() +
  theme(legend.position = c(0.9,0.15))  

png(filename="Figure3_cap15.png", type="cairo",units="px", width=5600, 
    height=3000, res=600, bg="transparent")
b5
dev.off() 
```

```{r}
grid.arrange(b1, b2, b3, ncol = 3)
```